from enum import Enum
import numpy as np

class ANTI_ALIASING_ALGORITHM(Enum):
    NONE = 0
    GRID = 1
    ROTATED_GRID = 2


# MIRROR REFLECTION DEPTH (1 <=)
MAX_DEPTH = 4

# PERCEIVED BRIGHTNESS THRESHOLD (0.0 - 1.0)
BRIGHTNESS_THRESHOLD = 0.4

# SET SUPERSAMPLING_SCALE TO 1 TO TURN OFF 
SUPERSAMPLING_SCALE = 1 # 1 <= 
AA_ALGORITHM = ANTI_ALIASING_ALGORITHM.GRID

# ROTATED GRID ALGORITHM SETTINGS
ROT_GRID_ANGLE = np.arctan(-1/2)
ROT_GRID_SCALE = np.sqrt(5)/2

