name: raytracer
channels:
  - anaconda
  - conda-forge
dependencies:
  - python=3.10.0
  - pip
  - nb_conda_kernels
  - pip:
    - ipywidgets
    - matplotlib
    - nbconvert
    - notebook
    - numpy
    - pillow
    - tifffile
    - ipympl
    - nodejs-bin
